In [2]:
import numpy as np
import pandas as pd

In [22]:
dataset = pd.read_csv('../0_datasets/credit_data.csv')
dataset.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

In [23]:
dataset.describe()

i#clientid        income          age          loan    c#default
count  2000.000000   2000.000000  1997.000000   2000.000000  2000.000000
mean   1000.500000  45331.600018    40.807559   4444.369695     0.141500
std     577.494589  14326.327119    13.624469   3045.410024     0.348624
min       1.000000  20014.489470   -52.423280      1.377630     0.000000
25%     500.750000  32796.459717    28.990415   1939.708847     0.000000
50%    1000.500000  45789.117313    41.317159   3974.719419     0.000000
75%    1500.250000  57791.281668    52.587040   6432.410625     0.000000
max    2000.000000  69995.685578    63.971796  13766.051239     1.000000

In [24]:
X = dataset.iloc[:, 1:4].values
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [25]:
y = dataset.iloc[:, 4].values
y

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [26]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import VarianceThreshold

In [27]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
X

array([[0.9231759 , 0.95743135, 0.58883739],
       [0.28812165, 0.86378597, 0.47682695],
       [0.74633429, 0.99257918, 0.58262011],
       ...,
       [0.48612202, 0.69109837, 0.40112895],
       [0.47500998, 1.        , 0.1177903 ],
       [0.98881367, 0.93282208, 0.53597028]])

In [28]:
selecao = VarianceThreshold(threshold=0.027)
X_novo = selecao.fit_transform(X)
X_novo

array([[0.9231759 , 0.58883739],
       [0.28812165, 0.47682695],
       [0.74633429, 0.58262011],
       ...,
       [0.48612202, 0.40112895],
       [0.47500998, 0.1177903 ],
       [0.98881367, 0.53597028]])

In [29]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

In [34]:
naive_bayes_sem_selecao = GaussianNB()
naive_bayes_sem_selecao.fit(X, y)
naive_bayes_sem_selecao_prev = naive_bayes_sem_selecao.predict(X)
accuracy_score(naive_bayes_sem_selecao_prev, y)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [32]:
naive_bayes_com_selecao = GaussianNB()
naive_bayes_com_selecao.fit(X_novo, y)
naive_bayes_com_selecao_prev = naive_bayes_com_selecao.predict(X_novo)
accuracy_score(naive_bayes_com_selecao_prev, y)

0.8475