In [23]:
import numpy as np
import pandas as pd

In [4]:
np.random.rand(50)

array([0.97899416, 0.65317026, 0.69004671, 0.79578111, 0.37304824,
       0.82443886, 0.87724198, 0.42179154, 0.64157854, 0.81743607,
       0.65944802, 0.4759833 , 0.42647656, 0.84408913, 0.35072366,
       0.74738556, 0.66419462, 0.34876986, 0.70569485, 0.92060828,
       0.58107212, 0.2005371 , 0.94683944, 0.64502104, 0.48451485,
       0.61100656, 0.98292727, 0.5380855 , 0.39756688, 0.1186103 ,
       0.06003516, 0.33519447, 0.40869019, 0.55817091, 0.69088364,
       0.00305013, 0.46209927, 0.91677742, 0.44164443, 0.40032661,
       0.06534227, 0.43722328, 0.37121063, 0.89073734, 0.25174429,
       0.65859291, 0.03443597, 0.00826932, 0.42487856, 0.1133924 ])

In [17]:
np.random.randint(0,2)

1

In [22]:
dados = {
    'a': np.random.rand(20),
    'b': np.array([0.5]*20),
    'class': np.random.randint(0, 2, size=20)
}
dados

{'a': array([0.55102227, 0.2130607 , 0.02776961, 0.55697584, 0.59397614,
        0.35369656, 0.86545919, 0.59050423, 0.88278708, 0.54689239,
        0.89794359, 0.85880909, 0.31060021, 0.52835686, 0.985021  ,
        0.86901228, 0.08346521, 0.8078223 , 0.5046957 , 0.77070682]),
 'b': array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]),
 'class': array([0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0])}

In [25]:
dataset = pd.DataFrame(dados)
dataset.head()

a    b  class
0  0.551022  0.5      0
1  0.213061  0.5      1
2  0.027770  0.5      0
3  0.556976  0.5      1
4  0.593976  0.5      1

In [26]:
dataset.describe()

a     b      class
count  20.000000  20.0  20.000000
mean    0.589929   0.5   0.250000
std     0.281622   0.0   0.444262
min     0.027770   0.5   0.000000
25%     0.466946   0.5   0.000000
50%     0.573740   0.5   0.000000
75%     0.860472   0.5   0.250000
max     0.985021   0.5   1.000000

In [27]:
np.var(dataset['a']), np.var(dataset['b'])

(0.07534543280345288, 0.0)

In [29]:
# Desvio Padrão
0.07534543280345288**(1/2), 0.0**(1/2)

(0.27449122536695575, 0.0)

In [31]:
X = dataset.iloc[:, 0:2].values
X

array([[0.55102227, 0.5       ],
       [0.2130607 , 0.5       ],
       [0.02776961, 0.5       ],
       [0.55697584, 0.5       ],
       [0.59397614, 0.5       ],
       [0.35369656, 0.5       ],
       [0.86545919, 0.5       ],
       [0.59050423, 0.5       ],
       [0.88278708, 0.5       ],
       [0.54689239, 0.5       ],
       [0.89794359, 0.5       ],
       [0.85880909, 0.5       ],
       [0.31060021, 0.5       ],
       [0.52835686, 0.5       ],
       [0.985021  , 0.5       ],
       [0.86901228, 0.5       ],
       [0.08346521, 0.5       ],
       [0.8078223 , 0.5       ],
       [0.5046957 , 0.5       ],
       [0.77070682, 0.5       ]])

In [34]:
from sklearn.feature_selection import VarianceThreshold

In [39]:
selecao = VarianceThreshold(threshold=0.07)
X_novo = selecao.fit_transform(X)
X_novo

array([[0.55102227],
       [0.2130607 ],
       [0.02776961],
       [0.55697584],
       [0.59397614],
       [0.35369656],
       [0.86545919],
       [0.59050423],
       [0.88278708],
       [0.54689239],
       [0.89794359],
       [0.85880909],
       [0.31060021],
       [0.52835686],
       [0.985021  ],
       [0.86901228],
       [0.08346521],
       [0.8078223 ],
       [0.5046957 ],
       [0.77070682]])

In [42]:
X_novo.shape

(20, 1)

In [43]:
selecao.variances_

array([0.07534543, 0.        ])

In [44]:
indices = np.where(selecao.variances_ > 0.07)
indices

(array([0], dtype=int64),)