## Regressão Múltipla

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [28]:
dataset = pd.read_csv('../0_datasets/house_prices.csv')
dataset.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [29]:
dataset.drop(labels=['id','date','sqft_living15','sqft_lot15'], axis=1, inplace=True)
dataset.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [30]:
X = dataset.iloc[:, 1:17].values
y = dataset.iloc[:, 0].values

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [32]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=0.2, random_state=1)

regressor = LinearRegression()
regressor.fit(X_treinamento, y_treinamento)

LinearRegression()

In [33]:
regressor.score(X_treinamento, y_treinamento)

0.7028464225751405

In [34]:
regressor.score(X_teste, y_teste)

0.6849876187392667

In [35]:
previsoes = regressor.predict(X_teste)
previsoes, y_teste

(array([ 630973.06582376,  480306.64680126,  705980.02289294, ...,
         361324.31649164, 1384852.19057864,  371113.74405643]),
 array([ 459000.,  445000., 1057000., ...,  260000., 1795000.,  418000.]))

In [36]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [37]:
mean_absolute_error(y_teste, previsoes)

130070.25300649341

In [38]:
mean_squared_error(y_teste, previsoes)

54371442904.1433

##### Seleção de atributos

In [43]:
from sklearn.feature_selection import SelectFdr, f_regression

selecao = SelectFdr(f_regression, alpha= 0.0)
X_novo = selecao.fit_transform(X,y)
X.shape, X_novo.shape

((21613, 16), (21613, 9))

In [45]:
selecao.pvalues_

array([0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 7.97250451e-040,
       1.58101007e-322, 0.00000000e+000, 0.00000000e+000, 8.93565406e-008,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.92987281e-015,
       1.02134789e-077, 5.01105043e-015, 0.00000000e+000, 1.47509222e-003])

In [46]:
colunas = selecao.get_support()
colunas

array([ True,  True,  True, False, False,  True,  True, False,  True,
        True,  True, False, False, False,  True, False])

In [47]:
dataset.columns[1:17][colunas==True]

Index(['bedrooms', 'bathrooms', 'sqft_living', 'waterfront', 'view', 'grade',
       'sqft_above', 'sqft_basement', 'lat'],
      dtype='object')

In [48]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X_novo, y, test_size=0.2, random_state=1)

regressor2 = LinearRegression()
regressor2.fit(X_treinamento, y_treinamento)

LinearRegression()

In [49]:
regressor2.score(X_treinamento, y_treinamento)

0.6600803804949469

In [50]:
regressor2.score(X_teste, y_teste)

0.6444774803577349