In [3]:
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv('../0_datasets/credit_data.csv')
dataset.shape

(2000, 5)

In [9]:
dataset.dropna(inplace=True)
dataset.shape

(1997, 5)

In [10]:
dataset.head()

i#clientid        income        age         loan  c#default
0           1  66155.925095  59.017015  8106.532131          0
1           2  34415.153966  48.117153  6564.745018          0
2           3  57317.170063  63.108049  8020.953296          0
3           4  42709.534201  45.751972  6103.642260          0
4           5  66952.688845  18.584336  8770.099235          1

### Sem pradronização

In [6]:
X = dataset.iloc[:, 1:4].values
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [8]:
y = dataset.iloc[:, 4].values
y

array([0, 0, 0, ..., 1, 0, 0], dtype=int64)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                   stratify=y)

In [14]:
# Salários da base de treinamento
np.mean(X_train[0]), np.median(X_train[0]), np.std(X_train[0])

(11871.569738482858, 4589.26726538164, 13647.086126727303)

In [19]:
# Salários da base de testes
np.mean(X_test[0]), np.median(X_test[0]), np.std(X_test[0])

(24162.12181501016, 4325.09926791081, 31127.752810792485)

In [18]:
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
previsoes = knn.predict(X_test)

In [21]:
accuracy_score(y_test, previsoes)

0.8425

### Com padronização

In [23]:
from sklearn.preprocessing import StandardScaler

In [24]:
z_score_train = StandardScaler()
z_score_test = StandardScaler()

X_train_p = z_score_train.fit_transform(X_train)
X_test_p = z_score_test.fit_transform(X_test)

In [25]:
X_train_p, X_test_p

(array([[-0.99701708, -0.50404812,  0.04991838],
        [-1.1440427 ,  1.5690499 , -1.12292369],
        [-0.14212983, -0.44372127,  0.76337932],
        ...,
        [ 0.74476391, -0.46224229, -0.14521886],
        [ 1.06409244,  0.55284073,  2.01456212],
        [ 0.04638133, -1.22646362, -0.03841581]]),
 array([[ 1.63660644,  0.4872041 , -0.05318296],
        [ 0.62720027,  0.64953558, -1.21468162],
        [ 1.47277317, -1.53007415, -1.46106544],
        ...,
        [ 0.80152153,  1.10776094,  0.80788283],
        [-1.34954559, -1.55218939, -1.11117175],
        [-0.00761255, -1.53418114, -0.92469013]]))

In [28]:
min(X_train_p[0]), max(X_train_p[0]), min(X_test_p[0]), max(X_test_p[0])

(-0.9970170776273112,
 0.049918379294931536,
 -0.05318296259057243,
 1.6366064390969552)

In [36]:
# Salários da base de treinamento
np.mean(X_train_p), np.median(X_train_p), np.std(X_train_p)

(-1.3762965117624148e-15, -0.04250273173047784, 0.9999999999999996)

In [35]:
# Salários da base de testes
np.mean(X_test_p), np.median(X_test_p), np.std(X_test_p)

(-2.7385501274087196e-16, -0.013926963376722109, 1.0000000000000002)

In [37]:
knn = KNeighborsClassifier()
knn.fit(X_train_p, y_train)
previsoes = knn.predict(X_test_p)

In [39]:
accuracy_score(y_test, previsoes)

0.9725